print( [1, "paris", -9.8, 3>5 , (2+2)*2 ] )
print( [1, "paris", -9.8, 3>5 , (2+2)*2 ][3]   )
print( [1, "paris", -9.8, 3>5 , (2+2)*2 ][0]   )
print( ["mercury", "venus", "earth", "mars", "jupiter", "saturn", "uranus", "neptune"] )
print( ["mercury", "venus", "earth", "mars", "jupiter", "saturn", "uranus", "neptune"][2] )
print({"name":"juhyon","age":21,"married":"false"})
print({"age":21,"name":"juhyon","married":"false"}["age"])
print({"age":21,"name":"juhyon","married":"false"}["married"])
